# Site settings
title: Forty
subtitle: by HTML5 UP
email: fatima.sanchez.garcia@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "fatimasanchez.ca" # the base hostname & protocol for your site
author:Fatima Sanchez
street_address: 
city: Ottawa  
state: ON 
zip_code: 
country: Canada
phone: (613) 407-0452

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/fatimasanchezgarcia/
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown

sass:
  style: compressed
